Added readme
hpvdt/website pull request #43
Opened 2023-12-02 20:31 UTC by GeorgeWangnottaken

Hi Savo, 

Here's a smol website readme. I'd appreciate any feedback on the content!

2023-12-06 02:20 UTC, savob requested changes
Can you please add a link to the plugin you use, and explain the directory structure as we chatted about.

2023-12-09 23:11 UTC, savob commented on team_members.html
> +                    <!-- <li>KAAIIIIIIIIIII (the cool one)</li> -->
Hrmmmmmmmmm :thinking:

2023-12-13 02:23 UTC, savob requested changes
There's something up with the main page regarding the exec photos. When the window is narrow it's okay, but when viewing full screen (at 1080p) they get seemingly randomly resized in front of or behind text.

2023-12-13 02:23 UTC, savob commented on README.md
> +Contact me on the HPVDT Discord or at <georgez.wang@mail.utoronto.ca> if you have questions or ideas to add to the website!
Let's remove your personal email from this. We have a @hpvdt/webmasters tag that can be used to reach us or list one of the team emails instead.

2023-12-15 02:19 UTC, GeorgeWangnottaken commented on README.md
> +Contact me on the HPVDT Discord or at <georgez.wang@mail.utoronto.ca> if you have questions or ideas to add to the website!
thanks for the feedback! the readme draft is legit enough for final review

2023-12-15 18:22 UTC, savob approved these changes
Looks good! 

Going to merge and delete this branch (so we can go back to having just a `dev` instead of `dev2`)

2023-12-15 18:23 UTC, merged